version: "3.8"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # 🔥 This gives Jenkins Docker access
    container_name: jenkins
    user: root  # Optional: make sure Jenkins has proper permissions

volumes:
  jenkins_home:
